### ISSUE TITLE
The current tab is not significantly different from other tabs

### ISSUE THREAD

**Issue by Alex-coder251** [hydescarf/Obsidian-Theme-Mado-11#15]
Sometimes it's hard for me to tell which one is the active tab.![image](https://user-images.githubusercontent.com/58896036/201457526-701d30bd-d87a-433e-887d-567e77752cd7.png)

Can you modify the tab style of the tab similar to the edge browser, please🥺
![image](https://user-images.githubusercontent.com/58896036/201457640-b0b3f61e-8a62-40df-865d-cfe14f7764b9.png)

**Comment by hydescarf** [comment]
![image](https://user-images.githubusercontent.com/56707567/201476667-a654c6e3-a4a2-4d73-bce9-b9e52d611cdf.png)
Would the above change look better?
(I assumed you were using translucent mode, so the above pic is currently in that mode)
I want to avoid implementing the shadow since the tabs are inside of the note itself, which might make it stand out too much.

**Comment by Alex-coder251** [comment]
Yes that Will be great 👍

**Comment by hydescarf** [comment]
The change is now live in the latest update!
Let me know the result of it!

**Comment by Alex-coder251** [comment]
it work! thx😭
