### ISSUE TITLE
Hidden layout conflict on MacOS

### ISSUE THREAD

**Issue by Benjamin-Medina** [hydescarf/Obsidian-Theme-Mado-11#19]
Hello, I appreciate your theme; both Mado and Mado Miniflow. There's something strickingly different between them, so well done!

I'm leaning towards Mado over Miniflow, but there's a conflict in buttons, which I've provided a picture below. I'm not big on keyboard shortcuts, yet, so one fail mouse click could mean closing Obsidian, rather than minimizing the sidebar. 

<img width="243" alt="Screen Shot 2023-02-06 at 11 53 20 AM" src="https://user-images.githubusercontent.com/118020281/217047937-5bd043e7-cb2e-4d9d-bb57-ad8f10f900c5.png">

All the best!

**Comment by hydescarf** [comment]
Thank you for the report!
I'd like to fix this but since I don't have a Mac on my side, I have to perform a live-debugging and would require your help to report the result back if possible.

I have made a small update to the theme, please try it out and let me know the following:
- The overlapping issue on top-left corner buttons (your current issue)
- Any other possible issues you found (optional, also issues can be possibly found on top-left/top-right corner)

**Comment by Benjamin-Medina** [comment]
<img width="445" alt="Screen Shot 2023-02-09 at 2 20 26 PM" src="https://user-images.githubusercontent.com/118020281/217928176-76d76474-f600-44e4-bd94-45faf5c0a11f.png">
<img width="354" alt="Screen Shot 2023-02-09 at 2 20 35 PM" src="https://user-images.githubusercontent.com/118020281/217928184-54a9f6b7-a7a3-49e7-ae31-247f4156935c.png">

Thank you for the update. I see the icon is moved over from its previous spot.

**Comment by hydescarf** [comment]
Thank you for the report!
Another update is now live, it should fix the spacing fully now. Please give it a try and let me know the result!
I've also adjusted the Hidden File Explorer position as well, it should align with the spacing above it.

**Comment by Benjamin-Medina** [comment]
I'm sorry, but I've checked for updates inside of Obsidian, and none are shown.

**Comment by hydescarf** [comment]
In that case, can you try reinstalling the theme?

**Comment by Benjamin-Medina** [comment]
Ok I did that and here are the results. 

![Screen Shot 2023-02-11 at 4 41 10 PM](https://user-images.githubusercontent.com/118020281/218284102-2cee5780-ea8c-40e9-9017-8742062d8de3.png)

![Screen Shot 2023-02-11 at 4 41 02 PM](https://user-images.githubusercontent.com/118020281/218284111-fb34e35d-2ecf-4979-b8aa-8379ecb02486.png)

**Comment by hydescarf** [comment]
I see it's working! Thank you for the report!

I see not a big problem with the file overlapping the buttons, although technically it should be hidden (slide-up) by default, not sure why it's not working. It might require a lot of back and forth communication to adjust for that.

Do you plan to use this hidden layout, or the unhidden layout as shown in the picture on the first post? We can technically end the thread here since that's your main issue.

**Comment by hydescarf** [comment]
Closing thread as there seems to be no issue for now!
