### ISSUE TITLE
Large Outline pane spacing

### ISSUE THREAD

**Issue by midnightmercenary** [hydescarf/Obsidian-Theme-Mado-11#4]
I'm noticing very large spacing between headings in the Outline pane.

![image](https://user-images.githubusercontent.com/56935282/165307228-facf5d20-0b82-4d6b-9bdb-afc05c34f84d.png)

**Comment by hydescarf** [comment]
Are you perhaps using the outline pane on the left sidebar? May be related to https://github.com/hydescarf/Obsidian-Theme-Mado-11/issues/3 
Still waiting for a response before pushing the update, feel free to pitch in if it's similar to your issue.
Otherwise, please let me know the position of this pane on the app.

**Comment by hydescarf** [comment]
Closing issue as update is now live https://github.com/hydescarf/Obsidian-Theme-Mado-11/commit/08e58350b3986b969b6077ffa40c869b47cd19fd. Do let me know if the issue persists though.

**Comment by midnightmercenary** [comment]
No issue after update. Great work and thank you!
![image](https://user-images.githubusercontent.com/56935282/165616042-d4a5da56-f3df-45b0-bf59-721dedda3c50.png)
