### ISSUE TITLE
Remove top Toolbar

### ISSUE THREAD

**Issue by sasha6606** [hydescarf/Obsidian-Theme-Mado-11#9]
Hi. Thank you for a great theme for obsidian. Sorry, I'm not good at programming, what code data do I need to remove to hide the toolbar?
<img width="324" alt="2022-06-30 в 15 44 55" src="https://user-images.githubusercontent.com/108470558/176680909-418901b6-4dac-4d71-a408-b3b7382b2ff3.png">

**Comment by hydescarf** [comment]
Thank you, and it's alright!
If you mean you want to completely hide that out, so that even when you hovered, they will not display:

1. Go to your snippets folder (You can access it from your Settings > Appearance > CSS Snippets, then look for the folder icon and click on it to bring up the folder)
2. Make a new file that ends with .css _(eg. MadoToolbarHidden.css)_
3. Copy and paste the following:
    ```
    .workspace-split.mod-horizontal.mod-left-split .workspace-tab-header-container{
	    display:none;
    }
    ```
    This will hide the toolbars on the left-dock.
    But if you want to also hide them on the right-dock, apply the following instead:
    ```
    .workspace-split.mod-horizontal .workspace-tab-header-container{
	    display:none;
    }
    ```
4. Make sure to turn them on in your settings!

Let me know if it works!

**Comment by sasha6606** [comment]
It worked! Thank you so much
